import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import PageHero from "@/src/shared/ui/page-hero/PageHero"
import Providers from "../../providers"
import Footer from "@/src/components/footer/Footer"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PageHero title="Add Reminder" breadcrumb={["Home", "Reminder" ,"Add"]} />
        <Providers>{children}</Providers>
        <Footer />
        </body>
    </html>
  )
}