import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext"
import Footer from "../components/footer/Footer";
import Header from "../components/Header";
import ThemeRegistry from "./theme-registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  <html lang="en">
    <body
      className={`${roboto.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <ThemeRegistry>
        <AuthProvider>{children}</AuthProvider>
      </ThemeRegistry>
    </body>
  </html>

  )
}